runtime:
  cache_dir: ./.cache/antora

site:
  title: Red Hat Single Sign-On Workshop
  url: https://olleb.com/rhsso-workshop
  start_page: sso-workshop::index.adoc

content:
  sources:
    - url: ./
      start_path: documentation

asciidoc:
  attributes:
    release-version: main
    page-pagination: true
    openshift-version: '4.12'
    sso-version: '7.6'
    freeipa-version: '4.9.8'
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/aolle/rhd-tutorial-ui/releases/download/v0.2.0/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: partials/toolbar.hbs
      contents: ./supplemental-ui/partials/toolbar.hbs
    - path: .nojekyll
    - path: ui.yml
      contents: "static_files: [ .nojekyll ]"

output:
  dir: ./gh-pages
