= FAQs & Troubleshooting
include::_attributes.adoc[]

This section provides answers to frequently asked questions and common troubleshooting topics related to Red Hat Single Sign-On (RH-SSO) and its integration in OpenShift environments.

== Which Keycloak version is this SSO based on?

You can verify the base Keycloak version used by your Red Hat Single Sign-On (RH-SSO) release at:

https://access.redhat.com/articles/2342881[Red Hat Single Sign-On Component Details]

== How to Extend the SSO Image

To properly customize the Red Hat Single Sign-On OpenShift image using the S2I strategy, refer to:

* https://access.redhat.com/solutions/3911211[Running JBoss CLI commands on extended JBoss EAP 7 OpenShift Image]

* https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.4/html-single/getting_started_with_jboss_eap_for_openshift_container_platform/index#s2i_modules_drivers_deployments[Configuring the JBoss EAP for OpenShift Image for Your Java Application]

== How to Register Provider Implementations

Provider implementations can be registered using either the *deployer* or *module* approaches.

For detailed guidance, refer to:

https://access.redhat.com/documentation/en-us/red_hat_single_sign-on/7.6/html/server_developer_guide/providers#registering_provider_implementations[Registering provider implementations]

== How to Obtain Admin Credentials

Admin credentials are stored in the following environment variables within the `DeploymentConfig` (or Pod):

* `SSO_ADMIN_USERNAME`
* `SSO_ADMIN_PASSWORD`

== How to Enable TRACE Logging

For instructions on enabling TRACE-level logging in Red Hat SSO, see:

https://access.redhat.com/solutions/3234951
